services:
  snuuper-interno:
    image: us-central1-docker.pkg.dev/snuuper-01/snuuper/snuuper-interno:latest
    container_name: snuuper-interno
    restart: always
    ports:
      - '5050'
    environment:
      - 'MONGODB_USERNAME=${MONGODB_USERNAME}'
      - 'MONGODB_PASSWORD=${MONGODB_PASSWORD}'
      - 'MONGODB_HOST=${MONGODB_HOST}'
      - 'MONGODB_PORT=${MONGODB_PORT}'
      - 'MONGODB_NAME=${MONGODB_NAME}'
      - 'PUBLIC_SITE_URL=${PUBLIC_SITE_URL}'
      - 'PUBLIC_SITE_DESCRIPTION=${PUBLIC_SITE_DESCRIPTION}'
      - 'PUBLIC_SITE_SHORTNAME=${PUBLIC_SITE_SHORTNAME}'
      - 'PUBLIC_SITE_KEYWORDS=${PUBLIC_SITE_KEYWORDS}'
      - 'GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}'
      - 'GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}'
      - 'GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}'
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
    networks:
      - interna-snuuper

  comms-cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwH07a-jp?wij8wp21*DkmamwMtyKVge8oLd2t81
    volumes:
      - comms_redis_cache:/data
    networks:
      - interna-snuuper

networks:
  interna-snuuper:
    external: true
    name: interna-snuuper
    driver: bridge
volumes:
  comms_redis_cache:
